name: Android Release Workflow

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths-ignore:
      - '.github/**'

  workflow_dispatch:
#    inputs:
#      releaseToGooglePlay:
#        description: 'Release to Google Play?'
#        required: true
#        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aab:
    name: Generate AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 21

      - name: Get tag name
        id: get_tag_name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      #      - name: Bump version
      #        uses: chkfung/android-version-actions@v1.1
      #        with:
      #          gradlePath: composeApp/build.gradle.kts
      #          versionCode: ${{github.run_number}}
      #          versionName: ${{ env.VERSION_TAG }}

      - name: Build Artifacts
        id: buildApks
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: composeApp:bundle

      - uses: kevin-david/zipalign-sign-android-release@v2.0.1
        name: Sign app APK
        id: twentyfourgame_sign
        with:
          releaseDirectory: composeApp/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Build Artifacts
        id: buildApks2
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: composeApp:assembleRelease

      - uses: kevin-david/zipalign-sign-android-release@v2.0.1
        name: Sign app APK2
        id: twentyfourgame_apk_sign
        with:
          releaseDirectory: composeApp/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        run: |
          cp ${{ steps.twentyfourgame_sign.outputs.signedReleaseFile }} twentyfourgame-release.aab
          cp ${{ steps.twentyfourgame_apk_sign.outputs.signedReleaseFile }} twentyfourgame-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Signed TwentyFourGame App
          path: twentyfourgame-release.aab

      - uses: actions/upload-artifact@v4
        with:
          name: Signed TwentyFourGame Apk
          path: twentyfourgame-release.apk

  #  apk:
  #    name: Generate APK
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - name: Setup JDK
  #        uses: actions/setup-java@v3
  #        with:
  #          distribution: adopt
  #          java-version: 21
  #
  #      - name: Get tag name
  #        id: get_tag_name
  #        run: |
  #          set -x
  #          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
  #
  #      #      - name: Bump version
  #      #        uses: chkfung/android-version-actions@v1.1
  #      #        with:
  #      #          gradlePath: composeApp/build.gradle.kts
  #      #          versionCode: ${{github.run_number}}
  #      #          versionName: ${{ env.VERSION_TAG }}
  #
  #      - name: Build Artifacts
  #        id: buildApks
  #        uses: gradle/gradle-build-action@v2
  #        with:
  #          gradle-version: current
  #          wrapper-cache-enabled: true
  #          dependencies-cache-enabled: true
  #          configuration-cache-enabled: true
  #          arguments: composeApp:assembleRelease
  #
  #      - uses: r0adkll/sign-android-release@v1
  #        name: Sign app APK
  #        id: twentyfourgame_apk_sign
  #        with:
  #          releaseDirectory: composeApp/build/outputs/apk/release/
  #          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
  #          alias: ${{ secrets.ALIAS }}
  #          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
  #          keyPassword: ${{ secrets.KEY_PASSWORD }}
  #
  #      - name: Clean up build artifacts
  #        run: |
  #          cp ${{ steps.twentyfourgame_apk_sign.outputs.signedReleaseFile }} twentyfourgame-release.apk
  #
  #      - uses: actions/upload-artifact@v3
  #        with:
  #          name: Signed TwentyFourGame Apk
  #          path: twentyfourgame-release.apk

  release:
    name: Release APK
    needs: [ aab ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Aab from build
        uses: actions/download-artifact@v4
        with:
          name: Signed TwentyFourGame App

      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: Signed TwentyFourGame Apk

      - name: Get tag name
        id: get_tag_name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ env.VERSION_TAG }}
          name: Release ${{ env.VERSION_TAG }}
          files: |
            twentyfourgame-release.aab
            twentyfourgame-release.apk

#  releaseToGooglePlay:
#    name: Release to Google Play
#    needs: apk
#    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.releaseToGooglePlay == 'true'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download APK from build
#        uses: actions/download-artifact@v3
#        with:
#          name: Signed Anagramer App
#
#      - uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#          packageName: com.programmersbox.twentyfourgame
#          releaseFiles: twentyfourgame-release.aab
#          track: production
#          status: inProgress
#          userFraction: 0.99